name: Linter and Tester

on:
  pull_request:
    types: [closed]

jobs:
  Linter:
    name: Linter code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 --exclude=venv,.venv,env

  Tester:
    name: Unit Testing
    runs-on: ubuntu-latest
    needs: Linter
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run Pytest
        run: pytest tests --maxfail=1 --disable-warnings -q
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
